#include "spi.h"
#include "sam.h"

#define MOSI 16
#define MISO 19
#define SCK 17
#define SS 18
#define RESET 22
#define ENABLE 6

void init_spi()
{
    // configure chip select pin
    PORT_REGS->GROUP[0].PORT_DIRSET = PORT_PA23;
    PORT_REGS->GROUP[0].PORT_OUTSET = PORT_PA23;

    // configure chip enable pin
    PORT_REGS->GROUP[0].PORT_DIRSET = PORT_PA06;

    // configure reset pin
    PORT_REGS->GROUP[0].PORT_DIRSET = PORT_PA22;

    // configure SPI pins
    PORT_REGS->GROUP[0].PORT_PINCFG[MOSI] = PORT_PINCFG_PMUXEN_Msk;
    PORT_REGS->GROUP[0].PORT_PINCFG[MISO] = PORT_PINCFG_PMUXEN_Msk;
    PORT_REGS->GROUP[0].PORT_PINCFG[SCK] = PORT_PINCFG_PMUXEN_Msk;
    // PORT_REGS->GROUP[0].PORT_PINCFG[SS] = PORT_PINCFG_PMUXEN_Msk;

    PORT_REGS->GROUP[0].PORT_PMUX[8] = PORT_PMUX_PMUXE_C | PORT_PMUX_PMUXO_C;
    PORT_REGS->GROUP[0].PORT_PMUX[9] = PORT_PMUX_PMUXO_C;

    MCLK_REGS->MCLK_APBAMASK |= MCLK_APBAMASK_SERCOM1_Msk;
    GCLK_REGS->GCLK_PCHCTRL[8] |= GCLK_PCHCTRL_CHEN_Msk;
    while ((GCLK_REGS->GCLK_PCHCTRL[8] & GCLK_PCHCTRL_CHEN_Msk) == 0)
        ;

    SERCOM1_REGS->SPIM.SERCOM_CTRLB = SERCOM_SPIM_CTRLB_CHSIZE_8_BIT | SERCOM_SPIM_CTRLB_RXEN_Msk;
    while ((SERCOM1_REGS->SPIM.SERCOM_SYNCBUSY) != 0U)
        ;

    SERCOM1_REGS->SPIM.SERCOM_BAUD = (uint8_t)SERCOM_SPIM_BAUD_BAUD(1UL);
    SERCOM1_REGS->SPIM.SERCOM_CTRLA = SERCOM_SPIM_CTRLA_MODE_SPI_MASTER | SERCOM_SPIM_CTRLA_DOPO_PAD0 | SERCOM_SPIM_CTRLA_DIPO_PAD3 | SERCOM_SPIM_CTRLA_CPOL_IDLE_LOW | SERCOM_SPIM_CTRLA_CPHA_LEADING_EDGE | SERCOM_SPIM_CTRLA_DORD_MSB | SERCOM_SPIM_CTRLA_ENABLE_Msk;
    while ((SERCOM1_REGS->SPIM.SERCOM_SYNCBUSY) != 0U)
        ;
}

uint8_t spi_write(uint8_t *data, uint8_t len)
{
    PORT_REGS->GROUP[0].PORT_OUTCLR = PORT_PA23;
    for (uint8_t i = 0; i < len; i++)
    {
        while ((SERCOM1_REGS->SPIM.SERCOM_INTFLAG & SERCOM_SPIM_INTFLAG_DRE_Msk) == 0U)
            ;
        SERCOM1_REGS->SPIM.SERCOM_DATA = data[i];
        while ((SERCOM1_REGS->SPIM.SERCOM_INTFLAG & SERCOM_SPIM_INTFLAG_TXC_Msk) == 0U)
            ;
    }
    return 0;
    PORT_REGS->GROUP[0].PORT_OUTSET = PORT_PA23;
}

uint8_t spi_read(uint8_t *data, uint8_t len)
{
    PORT_REGS->GROUP[0].PORT_OUTCLR = PORT_PA23;
    for (uint8_t i = 0; i < len; i++)
    {
        while ((SERCOM1_REGS->SPIM.SERCOM_INTFLAG & SERCOM_SPIM_INTFLAG_DRE_Msk) == 0U)
            ;
        SERCOM1_REGS->SPIM.SERCOM_DATA = 0;
        while ((SERCOM1_REGS->SPIM.SERCOM_INTFLAG & SERCOM_SPIM_INTFLAG_RXC_Msk) == 0U)
            ;
        data[i] = SERCOM1_REGS->SPIM.SERCOM_DATA;
    }
    PORT_REGS->GROUP[0].PORT_OUTSET = PORT_PA23;
    return 0;
}